#!/bin/bash
### BEGIN INIT INFO
# Provides:          runSearchNas
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run Search NAS web app and server if exists.
### END INIT INFO

serve -p 80 -s /home/pi/git/search-nas-react/build > /home/pi/react.out 2>&1 &
node /home/pi/git/search-nas-react/src/server.js > /home/pi/server.out 2>&1 &
